services:
  - type: web
    name: exchange-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_super_secret_key_here

      - key: DEBUG
        value: "False"

      - key: POSTGRES_DB
        value: exchangedb

      - key: POSTGRES_USER
        value: aziret

      - key: POSTGRES_PASSWORD
        value: Aziret7bklass

      - key: DB_HOST
        value: <RENDER_DB_INTERNAL_HOSTNAME>

      - key: DB_PORT
        value: 5432

      - key: ALLOWED_HOSTS
        value: your_render_service_name.onrender.com
